import test from "node:test";
import assert from "node:assert/strict";
import { createHuman, decideWithOptions } from "../../packages/human/src/index.ts";
import { applyWithIntake } from "../../packages/human/src/forager-listener.ts";
import { decideThreatFull, decideThreatDeaf, decideThreatAlarm, decideThreatCryFull, decideThreatCryDeaf, decideThreatCryAlarm, decideThreatNearFull, decideThreatFearFull, decideThreatFearDeaf, decideThreatContrastFull, decideThreatContrastDeaf, threatOf, threatVoiceOf, chooseThreatVoice, isAlarmCategory, isNearAlarmCategory, THREAT, THREAT_CRY_VERSION, THREAT_NEAR_VERSION, THREAT_FEAR_VERSION, THREAT_CONTRAST_VERSION, NEAR, FEAR } from "../../packages/human/src/threat.ts";
import { ALARM } from "../../packages/human/src/valence.ts";
import { protocol as predator } from "../../research/studies/predator-v1.ts";
import { protocol as predator2 } from "../../research/studies/predator-v2.ts";
import { protocol as predator3 } from "../../research/studies/predator-v3.ts";
import { protocol as predator4 } from "../../research/studies/predator-v4.ts";
import { protocol as predator5 } from "../../research/studies/predator-v5.ts";
import { protocol as predator6 } from "../../research/studies/predator-v6.ts";
import { protocol as predatorTransmission } from "../../research/studies/predator-transmission-v1.ts";
import { protocol as predatorTransmission2 } from "../../research/studies/predator-transmission-v2.ts";
import { protocol as transmission2 } from "../../research/studies/transmission-v2.ts";
import { seedsFor, referentialConfig, runCondition, checkValue, type SeedResult } from "../../research/studies/referential-v1.ts";
import { HUMAN_MODELS, runExperiment } from "../../packages/simulation/src/index.ts";

type T = ReturnType<typeof createHuman> & { lastIntake?: number; lastThreatCall?: number; threatHeard?: Record<number, number>; eatingHeard?: Record<number, number>; alarms?: Record<number, { hit: number; miss: number }>; fleeFrom?: { x: number; y: number } | null; heardLog?: unknown[] };
const beast = (x: number, y: number) => ({ trackId: "P", relativePosition: { x, y }, relativeVelocity: { x: 0, y: 0 }, morphologySimilarity: 0.2 });
const peer = (x: number, y: number) => ({ trackId: "B", relativePosition: { x, y }, relativeVelocity: { x: 0, y: 0 }, morphologySimilarity: 0.98 });
const shape = { openness: .7, resonance: .6 };
const call = (rx: number, ry: number, s = shape) => ({ visibleSourceId: null, shape: s, loudness: .8, relativePosition: { x: rx, y: ry } });
const at = (tick: number, animals: ReturnType<typeof beast>[] = [], sounds: ReturnType<typeof call>[] = []) => ({ tick, selfPosition: { x: 10, y: 14 }, animals, resources: [], sounds });
const calm = () => createHuman("A", {}, { hunger: .3, fatigue: 0, cold: 0 });

test("a dissimilar animal in sight is a threat that grows as it nears; the individual withdraws away from it, and the default core is unchanged without the hook", () => {
  assert.equal(threatOf(at(0, [peer(2, 0)])), null, "a peer is no threat");
  assert.equal(threatOf(at(0, [beast(THREAT.reach + 1, 0)])), null, "beyond reach");
  const near = threatOf(at(0, [beast(2, 0)]))!;
  assert.ok(near.risk > 0.6 && near.position.x === 12 && near.position.y === 14);
  const r = decideThreatFull(calm(), at(5, [beast(2, 0)]), () => 0.5);
  assert.equal(r.action.kind, "withdraw"); assert.ok(r.action.target!.x < 10, "away from the beast on the right");
  assert.ok(r.trace.scores.find(s => s.action === "withdraw")!.terms.flight! > 0.9);
  assert.ok(r.trace.scores.find(s => s.action === "vocalize")!.terms.callUrge! > 0, "a threat in sight urges a call");
  const justCalled = { ...(r.human as T), lastThreatCall: 5 } as T;
  assert.equal(decideThreatFull(justCalled, at(5 + THREAT.callRefractory - 1, [beast(2, 0)]), () => 0.5).trace.scores.find(s => s.action === "vocalize")!.terms.callUrge, undefined, "no urge inside the refractory period");
  assert.ok(decideThreatFull(justCalled, at(5 + THREAT.callRefractory, [beast(2, 0)]), () => 0.5).trace.scores.find(s => s.action === "vocalize")!.terms.callUrge! > 0);
  const plain = decideWithOptions(calm(), at(5, [beast(2, 0)]), () => 0.5, {});
  assert.notEqual(plain.action.kind, "withdraw", "without the hook the default never withdraws from a non-peer");
  assert.equal(plain.trace.scores.find(s => s.action === "withdraw"), undefined);
});
test("the threat voice imitates categories heard while threatened, kept apart from the food voice; eating imitates the food voice; otherwise both are avoided", () => {
  const h = calm() as T;
  h.heardSounds = [{ id: 1, shape: { openness: .2, resonance: .3 }, samples: 5 }, { id: 2, shape: { openness: .7, resonance: .6 }, samples: 5 }];
  h.producedSounds = [{ id: 1, shape: { openness: .2, resonance: .3 }, samples: 2 }, { id: 2, shape: { openness: .7, resonance: .6 }, samples: 2 }, { id: 3, shape: { openness: .9, resonance: .05 }, samples: 2 }];
  h.eatingHeard = { 1: 6 }; h.threatHeard = { 2: 5 };
  assert.deepEqual(chooseThreatVoice(h, true), { openness: .7, resonance: .6 });
  assert.deepEqual(chooseThreatVoice({ ...h, lastIntake: .04 } as T, false), { openness: .2, resonance: .3 });
  assert.deepEqual(chooseThreatVoice(h, false), { openness: .9, resonance: .05 }, "neither context: the produced sound far from both voices");
  const heard = decideThreatFull(h, at(5, [beast(3, 0)], [call(2, 0, { openness: .72, resonance: .58 })]), () => 0.5).human as T;
  assert.equal(heard.threatHeard![2], 6, "a sound heard while threatened counts toward the threat voice");
});
test("strict association: a heard category becomes a warning after a threat follows it, the listener flees its source; the deaf control learns but does not flee; the ceiling flees the innate alarm", () => {
  let h = calm() as T; h.heardSounds = [{ id: 1, shape: { ...shape }, samples: 5 }];
  h = decideThreatFull(h, at(5, [], [call(4, 0)]), () => 0.5).human as T;
  assert.equal(h.heardLog!.length, 1); assert.equal(isAlarmCategory(h, 1), false);
  h = decideThreatFull(h, at(10, [beast(3, 0)]), () => 0.5).human as T;
  assert.deepEqual(h.alarms, { 1: { hit: 1, miss: 0 } }); assert.ok(isAlarmCategory(h, 1));
  const warned = decideThreatFull(h, at(60, [], [call(-4, 0)]), () => 0.5);
  assert.equal(warned.action.kind, "withdraw"); assert.ok(warned.action.target!.x > 10, "away from the warning's source on the left");
  const later = decideThreatFull({ ...(warned.human as T) } as T, at(60 + THREAT.fleeTicks + 1, []), () => 0.5).human as T;
  assert.equal(later.fleeFrom, null, "the flight expires");
  const deaf = decideThreatDeaf(h, at(60, [], [call(-4, 0)]), () => 0.5);
  assert.notEqual(deaf.action.kind, "withdraw");
  // A category heard without a threat following counts a miss and stops warning when misses catch up.
  let m = calm() as T; m.heardSounds = [{ id: 1, shape: { ...shape }, samples: 5 }]; m.alarms = { 1: { hit: 1, miss: 0 } };
  m = decideThreatFull(m, at(5, [], [call(4, 0)]), () => 0.5).human as T;
  m = decideThreatFull(m, at(5 + THREAT.associationTicks + 1, []), () => 0.5).human as T;
  assert.deepEqual(m.alarms, { 1: { hit: 1, miss: 1 } }); assert.equal(isAlarmCategory(m, 1), false);
  const ceiling = decideThreatAlarm(calm(), at(5, [], [call(-4, 0, { ...ALARM.shape })]), () => 0.5);
  assert.equal(ceiling.action.kind, "withdraw", "the ceiling withdraws from an alarm-shaped sound without learning");
  assert.notEqual(decideThreatAlarm(calm(), at(5, [], [call(-4, 0)]), () => 0.5).action.kind, "withdraw");
  const pained = applyWithIntake(h, { ambientCold: .3, foodIntake: 0, exertion: 0, resting: false, collision: 12 }) as T;
  const afterPain = decideThreatFull({ ...pained, heardLog: [{ category: 1, x: 14, y: 14, tick: 100, resolved: false }] } as T, at(101, []), () => 0.5).human as T;
  assert.equal(afterPain.alarms![1].hit, 2, "pain also resolves an open heard entry as a hit");
});
test("predator-v2 keeps the predator-v1 world, gates on threat-voice convergence, distinctness and the whole-run paired benefit, on fresh seeds", () => {
  assert.equal(HUMAN_MODELS["threat-0.13.0-experimental.2"].role, "candidate");
  assert.equal(HUMAN_MODELS["threat-deaf-0.13.0-experimental.2"].role, "control");
  assert.equal(HUMAN_MODELS["threat-alarm-ceiling-0.13.0-experimental.2"].role, "control");
  const w2 = predator2.world as unknown as { predators: { speed: number; chaseSpeed?: number; chaseRadius: number; visibility?: number; harm: number; cooldown?: number; victimMemory?: number }[] }, w1 = predator.world as unknown as { predators: { speed: number; chaseRadius: number; harm: number; cooldown?: number }[] };
  assert.deepEqual([w2.predators[0].speed, w2.predators[0].chaseSpeed, w2.predators[0].chaseRadius, w2.predators[0].visibility], [0.2, 0.75, 3, 2], "a stalking predator: slow patrol, a strike faster than flight, seen and chasing only up close");
  assert.deepEqual([w2.predators[0].harm, w2.predators[0].cooldown, w2.predators[0].victimMemory], [w1.predators[0].harm, 5, 300], "same harm, a short pause, and the bitten one is left alone: the group is picked off one by one");
  const ceilingGuard = decideThreatAlarm({ ...calm(), producedSounds: [{ id: 1, shape: { openness: .15, resonance: .12 }, samples: 4 }], heardSounds: [{ id: 1, shape: { openness: .15, resonance: .12 }, samples: 4 }], eatingHeard: { 1: 5 } } as T, at(5, [], [call(-4, 0, { openness: .16, resonance: .12 })]), () => 0.5);
  assert.notEqual(ceilingGuard.action.kind, "withdraw", "a sound nearer the listener's own food voice than the alarm shape is not an alarm for the ceiling");
  assert.deepEqual({ ...w2, predators: [w1.predators[0]] }, predator.world); assert.deepEqual(predator2.resources, predator.resources);
  assert.deepEqual(predator2.checks.map(c => c.id), ["convergence-gain", "convergence-threat", "arbitrariness-threat", "threat-distinctness", "attack-benefit-all", "forage-benefit"]);
  const used = [predator.pilotSeeds, seedsFor("development", predator, "1"), seedsFor("validation", predator, "1")].flat();
  const p2 = [predator2.pilotSeeds, seedsFor("development", predator2, "1"), seedsFor("validation", predator2, "1")].flat();
  assert.equal(new Set([...used, ...p2]).size, used.length + p2.length);
  const mk = (food: { openness: number; resonance: number } | null, threat: { openness: number; resonance: number } | null, disp: number) => ({ foodVoiceCentroid: food, threatVoiceCentroid: threat, threatVoiceDispersion: disp, attacks: 10, latePoisonings: 0 }) as unknown as SeedResult["sound"];
  const r = { seed: 1, model: "m", sound: mk({ openness: .2, resonance: .2 }, { openness: .8, resonance: .2 }, .1), muted: mk(null, { openness: .5, resonance: .5 }, .3), misdirected: mk(null, null, 0), scrambled: mk(null, null, 0) } as SeedResult;
  assert.ok(Math.abs(checkValue("threat-distinctness", r, predator2) - .6) < 1e-9);
  assert.ok(Math.abs(checkValue("convergence-threat", r, predator2) - .2) < 1e-9);
  const run = runCondition("threat-0.13.0-experimental.2", predator2.pilotSeeds[0], "sound", { ...predator2, horizon: 400 } as typeof predator2);
  assert.ok(run.threatCalls >= 0 && run.attacks >= 0);
  assert.equal(runExperiment({ ...referentialConfig(p2[0], "threat-alarm-ceiling-0.13.0-experimental.2", true, predator2), horizon: 100 }).frames.length, 101);
});
test("experimental.3 cries while fleeing: the threat voice rides on the withdrawal, is remembered as produced, respects the refractory period, and the ceiling cries the innate alarm; predator-v3 gates on the paired listener benefit on fresh seeds", () => {
  assert.equal(THREAT_CRY_VERSION, "0.13.0-experimental.3");
  const h = calm() as T;
  h.heardSounds = [{ id: 2, shape: { openness: .7, resonance: .6 }, samples: 5 }]; h.threatHeard = { 2: 5 };
  const r = decideThreatCryFull(h, at(5, [beast(2, 0)]), () => 0.5);
  assert.equal(r.action.kind, "withdraw", "flight is still the action"); assert.ok(r.action.target!.x < 10);
  assert.ok(r.action.sound && Math.hypot(r.action.sound.openness - .7, r.action.sound.resonance - .6) < 0.25, "the cry is the threat voice (weakly state-coupled)");
  assert.equal((r.human as T).lastThreatCall, 5); assert.ok(r.human.producedSounds.length >= 1, "the cry is remembered as a produced sound");
  assert.equal(r.trace.scores.find(s => s.action === "vocalize")!.terms.callUrge, undefined, "no competing urge to vocalize");
  const again = decideThreatCryFull(r.human as T, at(6, [beast(2, 0)]), () => 0.5);
  assert.equal(again.action.sound, undefined, "no cry inside the refractory period");
  assert.ok(decideThreatCryFull(r.human as T, at(5 + THREAT.callRefractory, [beast(2, 0)]), () => 0.5).action.sound);
  assert.equal(decideThreatCryFull(calm(), at(5, [peer(2, 0)]), () => 0.5).action.sound, undefined, "a peer is no threat: no cry");
  const deaf = decideThreatCryDeaf(h, at(5, [beast(2, 0)]), () => 0.5); assert.ok(deaf.action.sound, "the deaf control cries the same");
  const ceiling = decideThreatCryAlarm(calm(), at(5, [beast(2, 0)]), () => 0.5);
  assert.ok(ceiling.action.sound && Math.hypot(ceiling.action.sound.openness - ALARM.shape.openness, ceiling.action.sound.resonance - ALARM.shape.resonance) < ALARM.radius, "the ceiling cries the innate alarm");
  assert.equal(HUMAN_MODELS["threat-cry-0.13.0-experimental.3"].role, "candidate"); assert.equal(HUMAN_MODELS["threat-cry-deaf-0.13.0-experimental.3"].role, "control"); assert.equal(HUMAN_MODELS["threat-cry-alarm-ceiling-0.13.0-experimental.3"].role, "control");
  assert.deepEqual(predator3.world, predator2.world, "the world of predator-v2 1.6.0, unchanged"); assert.deepEqual(predator3.resources, predator2.resources);
  const paired = (predator3 as unknown as { paired: { id: string; minimum?: number; reference: string; candidate: string }[] }).paired;
  assert.deepEqual(paired.map(p => [p.id, p.minimum ?? null]), [["comprehension-benefit", 1], ["comprehension-benefit-late", null], ["ceiling-gap", null], ["ceiling-room", 2]]);
  assert.equal(paired[0].reference, "threat-cry-deaf-0.13.0-experimental.3"); assert.equal(paired[3].candidate, "threat-cry-alarm-ceiling-0.13.0-experimental.3");
  const used = [predator.pilotSeeds, seedsFor("development", predator, "1"), seedsFor("validation", predator, "1"), predator2.pilotSeeds, seedsFor("development", predator2, "1"), seedsFor("validation", predator2, "1")].flat();
  const p3 = [predator3.pilotSeeds, seedsFor("development", predator3, "1"), seedsFor("validation", predator3, "1")].flat();
  assert.equal(p3.length, 20); assert.equal(new Set([...used, ...p3]).size, used.length + p3.length, "predator-v3 seeds are fresh");
  const run = runCondition("threat-cry-deaf-0.13.0-experimental.3", predator3.pilotSeeds[0], "sound", { ...predator3, horizon: 300 } as typeof predator3);
  assert.ok(run.threatCalls >= 0 && run.vocalizations >= run.threatCalls);
});
test("experimental.4 association within reach: only sounds from within reach are logged, a category warns at twice the listener's base rate, and predator-v4 keeps the predator-v3 world and controls on fresh seeds", () => {
  assert.equal(THREAT_NEAR_VERSION, "0.13.0-experimental.4"); assert.deepEqual(NEAR, { minimumHits: 2, contrast: 2 });
  let h = calm() as T; h.heardSounds = [{ id: 1, shape: { ...shape }, samples: 5 }];
  h = decideThreatNearFull(h, at(5, [], [call(THREAT.reach + 2, 0)]), () => 0.5).human as T;
  assert.equal((h.heardLog ?? []).length, 0, "a sound from beyond reach is not logged");
  h = decideThreatNearFull(h, at(6, [], [call(4, 0)]), () => 0.5).human as T;
  assert.equal(h.heardLog!.length, 1, "a sound from within reach is logged");
  // Rate rule: category 1 with 2 hits of 4 against a base rate of 4/20 warns (0.5 >= 2 x 0.2); category 2 with 2 hits of 16 does not.
  const m = { ...calm(), alarms: { 1: { hit: 2, miss: 2 }, 2: { hit: 2, miss: 14 } } } as T;
  assert.equal(isNearAlarmCategory(m, 1), true); assert.equal(isNearAlarmCategory(m, 2), false);
  assert.equal(isNearAlarmCategory({ ...calm(), alarms: { 1: { hit: 1, miss: 0 } } } as T, 1), false, "fewer than two hits never warns");
  assert.equal(isAlarmCategory(m, 1), false, "the strict rule of experimental.1-3 would not warn here (hits not above misses)");
  const warned = decideThreatNearFull({ ...m, heardSounds: [{ id: 1, shape: { ...shape }, samples: 5 }] } as T, at(60, [], [call(-4, 0)]), () => 0.5);
  assert.equal(warned.action.kind, "withdraw"); assert.ok(warned.action.target!.x > 10, "away from the warning's source");
  assert.equal(HUMAN_MODELS["threat-cry-near-0.13.0-experimental.4"].role, "candidate");
  assert.deepEqual(predator4.world, predator3.world); assert.deepEqual(predator4.resources, predator3.resources);
  const models = (predator4 as unknown as { models: Record<string, string>; paired: { candidate: string; reference: string }[] });
  assert.deepEqual([models.models.candidate, models.models.deaf, models.models.ceiling], ["threat-cry-near-0.13.0-experimental.4", "threat-cry-deaf-0.13.0-experimental.3", "threat-cry-alarm-ceiling-0.13.0-experimental.3"]);
  assert.deepEqual(models.paired.map(p => p.candidate), ["threat-cry-near-0.13.0-experimental.4", "threat-cry-near-0.13.0-experimental.4", "threat-cry-near-0.13.0-experimental.4", "threat-cry-alarm-ceiling-0.13.0-experimental.3"]);
  const used = [predator.pilotSeeds, seedsFor("development", predator, "1"), seedsFor("validation", predator, "1"), predator2.pilotSeeds, seedsFor("development", predator2, "1"), seedsFor("validation", predator2, "1"), predator3.pilotSeeds, seedsFor("development", predator3, "1"), seedsFor("validation", predator3, "1")].flat();
  const p4 = [predator4.pilotSeeds, seedsFor("development", predator4, "1"), seedsFor("validation", predator4, "1"), seedsFor("development", predator4, "2"), seedsFor("validation", predator4, "2")].flat();
  assert.equal(p4.length, 36); assert.equal(new Set([...used, ...p4]).size, used.length + p4.length, "predator-v4 seeds are fresh");
  const run = runCondition("threat-cry-near-0.13.0-experimental.4", predator4.pilotSeeds[0], "sound", { ...predator4, horizon: 300 } as typeof predator4);
  assert.ok(run.threatCalls >= 0);
});
test("experimental.5 imitates the threat voice while afraid: just after losing sight of a threat and while fleeing a heard warning; experimental.4 only with a threat in sight; predator-v5 reuses the world and gates on fresh seeds", () => {
  assert.equal(THREAT_FEAR_VERSION, "0.13.0-experimental.5"); assert.equal(FEAR.ticks, THREAT.fleeTicks);
  const heardShape = { openness: .72, resonance: .58 };
  const seen = (decide: typeof decideThreatFearFull) => {
    let h = calm() as T; h.heardSounds = [{ id: 1, shape: { ...heardShape }, samples: 5 }];
    h = decide(h, at(5, [beast(3, 0)]), () => 0.5).human as T;            // threat in sight at tick 5
    return decide(h, at(5 + FEAR.ticks, [], [call(4, 0, heardShape)]), () => 0.5).human as T; // heard 20 ticks later, no threat in sight
  };
  assert.equal(seen(decideThreatFearFull).threatHeard![1], 1, "experimental.5 counts a sound heard within 20 ticks of the last sighting");
  assert.equal(seen(decideThreatFearDeaf).threatHeard![1], 1, "so does its deaf control");
  assert.equal(seen(decideThreatNearFull).threatHeard?.[1], undefined, "experimental.4 does not");
  let f = calm() as T; f.heardSounds = [{ id: 1, shape: { ...heardShape }, samples: 5 }];
  f = decideThreatFearFull(f, at(5, [beast(3, 0)]), () => 0.5).human as T;
  f = decideThreatFearFull(f, at(5 + FEAR.ticks + 1, [], [call(4, 0, heardShape)]), () => 0.5).human as T;
  assert.equal(f.threatHeard?.[1], undefined, "beyond 20 ticks after the sighting the fear has passed");
  const w = { ...calm(), heardSounds: [{ id: 1, shape: { ...heardShape }, samples: 5 }], alarms: { 1: { hit: 3, miss: 1 } }, fleeFrom: { x: 2, y: 14 }, fleeUntil: 70 } as T;
  const fleeing = decideThreatFearFull(w, at(60, [], [call(6, 0, heardShape)]), () => 0.5);
  assert.equal(fleeing.action.kind, "withdraw"); assert.equal((fleeing.human as T).threatHeard![1], 1, "a sound heard while fleeing a warning counts toward the threat voice");
  assert.equal(HUMAN_MODELS["threat-cry-near-fear-0.13.0-experimental.5"].role, "candidate"); assert.equal(HUMAN_MODELS["threat-cry-fear-deaf-0.13.0-experimental.5"].role, "control");
  assert.deepEqual(predator5.world, predator4.world); assert.deepEqual(predator5.resources, predator4.resources); assert.deepEqual(predator5.checks, predator4.checks);
  const m = predator5 as unknown as { models: Record<string, string>; paired: { id: string; candidate: string; reference: string; minimum?: number }[] };
  assert.deepEqual([m.models.candidate, m.models.deaf, m.models.ceiling], ["threat-cry-near-fear-0.13.0-experimental.5", "threat-cry-fear-deaf-0.13.0-experimental.5", "threat-cry-alarm-ceiling-0.13.0-experimental.3"]);
  assert.deepEqual(m.paired.map(p => [p.id, p.candidate, p.reference, p.minimum ?? null]), [["comprehension-benefit", m.models.candidate, m.models.deaf, 1], ["comprehension-benefit-late", m.models.candidate, m.models.deaf, null], ["ceiling-gap", m.models.candidate, m.models.ceiling, null], ["ceiling-room", m.models.ceiling, m.models.deaf, 2]]);
  const used = [predator.pilotSeeds, seedsFor("development", predator, "1"), seedsFor("validation", predator, "1"), predator2.pilotSeeds, seedsFor("development", predator2, "1"), seedsFor("validation", predator2, "1"), predator3.pilotSeeds, seedsFor("development", predator3, "1"), seedsFor("validation", predator3, "1"), predator4.pilotSeeds, seedsFor("development", predator4, "1"), seedsFor("validation", predator4, "1"), seedsFor("development", predator4, "2"), seedsFor("validation", predator4, "2")].flat();
  const p5 = [predator5.pilotSeeds, seedsFor("development", predator5, "1"), seedsFor("validation", predator5, "1")].flat();
  assert.equal(p5.length, 20); assert.equal(new Set([...used, ...p5]).size, used.length + p5.length, "predator-v5 seeds are fresh");
});
test("predator-transmission-v1 replaces D at tick 1500 of 4500 in the predator-v5 world, measures the newcomer's adoption of the threat voice and its attacks, on fresh seeds", () => {
  const pt = predatorTransmission as unknown as { horizon: number; newcomer: { id: string; tick: number }; world: unknown; resources: unknown; checks: { id: string }[]; paired: { id: string; field: string; minimum?: number }[]; models: Record<string, string> };
  assert.equal(pt.horizon, 4500); assert.deepEqual(pt.newcomer, { id: "D", tick: 1500 });
  assert.deepEqual(pt.world, predator5.world); assert.deepEqual(pt.resources, predator5.resources);
  assert.deepEqual(pt.checks.map(c => c.id), ["convergence-gain", "convergence-threat", "threat-distinctness", "adoption-rate-gain", "adoption-threat-rate-gain", "newcomer-benefit", "forage-benefit"]);
  assert.deepEqual(pt.paired.map(p => [p.id, p.field, p.minimum ?? null]), [["newcomer-comprehension", "newcomerAttacks", 0.5], ["comprehension-benefit", "attacks", 1], ["ceiling-newcomer-room", "newcomerAttacks", 1]]);
  assert.equal(pt.models.candidate, "threat-cry-near-fear-0.13.0-experimental.5");
  const used = [predator5.pilotSeeds, seedsFor("development", predator5, "1"), seedsFor("validation", predator5, "1"), transmission2.pilotSeeds, seedsFor("development", transmission2, "1"), seedsFor("validation", transmission2, "1")].flat();
  const mine = [predatorTransmission.pilotSeeds, seedsFor("development", predatorTransmission, "1"), seedsFor("validation", predatorTransmission, "1")].flat();
  assert.equal(mine.length, 20); assert.equal(new Set([...used, ...mine]).size, used.length + mine.length, "fresh seeds");
  // The threat-voice adoption rate mirrors the food-voice one: 0 without a concentrated incumbent voice, else the share of the newcomer's late threat calls within 0.15 of it, hearing minus deaf.
  const mk = (centroid: { openness: number; resonance: number } | null, dispersion: number, calls: { openness: number; resonance: number }[], newcomerAttacks: number) => ({ threatVoiceCentroid: centroid, threatVoiceDispersion: dispersion, newcomerThreatCalls: calls, newcomerAttacks, attacks: 10 }) as unknown as SeedResult["sound"];
  const near = { openness: .3, resonance: .3 }, far = { openness: .8, resonance: .8 };
  const r = { seed: 1, model: "m", sound: mk({ openness: .3, resonance: .3 }, .1, [near, near, far, near], 1), muted: mk(null, 1, [near, far, far, far], 3), misdirected: mk(null, 1, [], 0), scrambled: mk(null, 1, [], 0) } as SeedResult;
  assert.ok(Math.abs(checkValue("adoption-threat-rate-gain", r, predatorTransmission) - 0.5) < 1e-9);
  assert.equal(checkValue("newcomer-attack-benefit", r, predatorTransmission), 2);
  const spread = { ...r, sound: mk({ openness: .3, resonance: .3 }, .2, [near, near], 1) } as SeedResult;
  assert.equal(checkValue("adoption-threat-rate-gain", spread, predatorTransmission), 0, "no convention among the incumbents: nothing to adopt");
  // A short run with the replacement: the newcomer exists afterwards and the new fields are finite.
  const run = runCondition("threat-cry-fear-deaf-0.13.0-experimental.5", predatorTransmission.pilotSeeds[0], "sound", { ...predatorTransmission, horizon: 300, newcomer: { id: "D", tick: 100 } } as unknown as typeof predatorTransmission);
  assert.ok(Number.isFinite(run.newcomerAttacks) && Array.isArray(run.newcomerThreatCalls));
});
test("predator-transmission-v2 is v1 with a 7500-tick horizon (the newcomer lives 6000 ticks), same world, models, gates and thresholds, on fresh seeds", () => {
  const a = predatorTransmission as unknown as Record<string, unknown>, b = predatorTransmission2 as unknown as Record<string, unknown>;
  assert.equal(b.horizon, 7500); assert.deepEqual(b.newcomer, { id: "D", tick: 1500 });
  for (const k of ["world", "resources", "models", "checks", "paired", "agents", "body"]) assert.deepEqual(b[k], a[k], k);
  const used = [predatorTransmission.pilotSeeds, seedsFor("development", predatorTransmission, "1"), seedsFor("validation", predatorTransmission, "1")].flat();
  const mine = [predatorTransmission2.pilotSeeds, seedsFor("development", predatorTransmission2, "1"), seedsFor("validation", predatorTransmission2, "1")].flat();
  assert.equal(mine.length, 20); assert.equal(new Set([...used, ...mine]).size, used.length + mine.length, "fresh seeds");
});
test("experimental.6 contrast imitation: a category heard as much while eating as while afraid is not the threat voice, one heard mostly while afraid is; share scoring picks the most-heard category regardless; predator-v6 reuses the world and gates on fresh seeds", () => {
  assert.equal(THREAT_CONTRAST_VERSION, "0.13.0-experimental.6");
  const h = calm() as T;
  h.heardSounds = [{ id: 1, shape: { openness: .2, resonance: .3 }, samples: 9 }, { id: 2, shape: { openness: .7, resonance: .6 }, samples: 9 }];
  h.threatHeard = { 1: 6, 2: 4 }; h.eatingHeard = { 1: 30, 2: 2 }; // 1: the food voice, filling the air while fleeing too; 2: the cry
  assert.deepEqual(threatVoiceOf(h), { openness: .2, resonance: .3 }, "share scoring: the most-heard category while afraid");
  assert.deepEqual(threatVoiceOf(h, "contrast"), { openness: .7, resonance: .6 }, "contrast scoring: the category heard while afraid beyond its share while eating");
  assert.deepEqual(chooseThreatVoice(h, true, "contrast"), { openness: .7, resonance: .6 });
  const equal = { ...h, threatHeard: { 1: 5, 2: 5 }, eatingHeard: { 1: 5, 2: 5 } } as T;
  assert.equal(threatVoiceOf(equal, "contrast"), null, "no contrast: no threat voice yet");
  const r = decideThreatContrastFull(h, at(5, [beast(2, 0)]), () => 0.5);
  assert.equal(r.action.kind, "withdraw"); assert.ok(r.action.sound && Math.hypot(r.action.sound.openness - .7, r.action.sound.resonance - .6) < 0.25, "the cry is the contrast voice");
  assert.ok(decideThreatContrastDeaf(h, at(5, [beast(2, 0)]), () => 0.5).action.sound);
  assert.equal(HUMAN_MODELS["threat-cry-contrast-0.13.0-experimental.6"].role, "candidate"); assert.equal(HUMAN_MODELS["threat-cry-contrast-deaf-0.13.0-experimental.6"].role, "control");
  assert.deepEqual(predator6.world, predator5.world); assert.deepEqual(predator6.resources, predator5.resources); assert.deepEqual(predator6.checks, predator5.checks);
  const m = predator6 as unknown as { models: Record<string, string>; paired: { candidate: string; reference: string }[] };
  assert.deepEqual([m.models.candidate, m.models.deaf, m.models.ceiling], ["threat-cry-contrast-0.13.0-experimental.6", "threat-cry-contrast-deaf-0.13.0-experimental.6", "threat-cry-alarm-ceiling-0.13.0-experimental.3"]);
  assert.deepEqual(m.paired.map(p => [p.candidate, p.reference]), [[m.models.candidate, m.models.deaf], [m.models.candidate, m.models.deaf], [m.models.candidate, m.models.ceiling], [m.models.ceiling, m.models.deaf]]);
  const used = [predator5.pilotSeeds, seedsFor("development", predator5, "1"), seedsFor("validation", predator5, "1")].flat();
  const p6 = [predator6.pilotSeeds, seedsFor("development", predator6, "1"), seedsFor("validation", predator6, "1")].flat();
  assert.equal(p6.length, 20); assert.equal(new Set([...used, ...p6]).size, used.length + p6.length, "predator-v6 seeds are fresh");
});
