import test from "node:test";
import assert from "node:assert/strict";
import { createHuman, applyPhysicalEffect } from "../../packages/human/src/index.ts";
import { advanceWorld, createWorld, WORLD_VERSION } from "../../packages/world/src/index.ts";
import { applyWithIntake } from "../../packages/human/src/forager-listener.ts";
import { valenceOf, valenceVoice, chooseValenceVoice, selectSafeFood, decideValence } from "../../packages/human/src/valence.ts";
import { protocol as valence } from "../../research/studies/valence-v1.ts";
import { protocol as v5 } from "../../research/studies/referential-v5.ts";
import { seedsFor, runCondition, checkValue, referentialConfig, type SeedResult } from "../../research/studies/referential-v1.ts";
import { HUMAN_MODELS, runExperiment, createSimulation, VERSIONS } from "../../packages/simulation/src/index.ts";

type V = ReturnType<typeof createHuman> & { lastIntake?: number; lastPoison?: number; valenceReferents?: { good: Record<number, { mean: number; variance: number; samples: number }>; bad: Record<number, { mean: number; variance: number; samples: number }> }; valenceHeard?: unknown; recentSounds?: unknown[] };
const effect = (foodIntake: number, poison = 0) => ({ ambientCold: .3, foodIntake, exertion: 0, resting: false, collision: 0, ...(poison ? { poison } : {}) });

test("world 0.5.0: a toxic patch poisons its eaters, spawned patches are toxic every n-th time, wholesome food never sets poison", () => {
  assert.equal(WORLD_VERSION, "0.5.0"); assert.equal(VERSIONS.contracts, "0.3.0");
  const animals = [{ id: "A", position: { x: 7, y: 5 } }];
  const toxic = createWorld(animals, { foodRegeneration: 0, foodSpawn: { amount: 1, radius: 2, depletedBelow: 0.01, positions: [{ x: 20, y: 3 }, { x: 5, y: 22 }], toxicEvery: 2 } }, [{ id: "f", kind: "food", position: { x: 7, y: 5 }, amount: 0.05, radius: 2, toxic: true }]);
  const step1 = advanceWorld(toxic, { A: { kind: "forage" } }, 0);
  assert.ok(Math.abs((step1.effects.A.poison ?? 0) - 0.04) < 1e-9 && Math.abs(step1.effects.A.foodIntake - 0.04) < 1e-9, "toxic intake is counted as both food and poison");
  const step2 = advanceWorld(step1.world, { A: { kind: "forage" } }, 1);
  assert.equal(step2.world.resources.at(-1)!.toxic, undefined, "the first spawned patch is wholesome");
  let w = step2.world; for (let t = 2; t < 40; t++) w = advanceWorld(w, { A: { kind: "forage", target: { x: 20, y: 3 } } }, t).world;
  const plain = createWorld(animals, {}, [{ id: "f", kind: "food", position: { x: 7, y: 5 }, amount: 1, radius: 2 }]);
  assert.equal(advanceWorld(plain, { A: { kind: "forage" } }, 0).effects.A.poison, undefined);
  const body = applyPhysicalEffect(createHuman("A"), effect(0.04, 0.04)).body;
  assert.ok(body.health < 1 - 0.005, "poison costs health");
  const fed = applyWithIntake(createHuman("A"), effect(0.04, 0.04)) as V;
  assert.equal(fed.lastPoison, 0.04); assert.equal(valenceOf(fed), "bad");
  assert.equal(valenceOf(applyWithIntake(createHuman("A"), effect(0.04)) as V), "good");
  assert.equal(valenceOf(applyWithIntake(createHuman("A"), effect(0)) as V), null);
});
test("the valence speaker imitates the good voice when eating well and the bad voice when poisoned, separates them, and avoids both otherwise", () => {
  const h = createHuman("A", {}, { hunger: .5 }) as V;
  h.heardSounds = [{ id: 1, shape: { openness: .2, resonance: .3 }, samples: 5 }, { id: 2, shape: { openness: .7, resonance: .6 }, samples: 5 }];
  h.producedSounds = [{ id: 1, shape: { openness: .2, resonance: .3 }, samples: 3 }, { id: 2, shape: { openness: .7, resonance: .6 }, samples: 3 }, { id: 3, shape: { openness: .9, resonance: .1 }, samples: 3 }];
  h.valenceReferents = { good: { 1: { mean: .7, variance: .1, samples: 4 } }, bad: { 2: { mean: .6, variance: .1, samples: 4 } } };
  assert.deepEqual(valenceVoice(h, "good"), { openness: .2, resonance: .3 }); assert.deepEqual(valenceVoice(h, "bad"), { openness: .7, resonance: .6 });
  assert.deepEqual(chooseValenceVoice({ ...h, lastIntake: .04, lastPoison: 0 } as V), { openness: .2, resonance: .3 });
  assert.deepEqual(chooseValenceVoice({ ...h, lastIntake: .04, lastPoison: .04 } as V), { openness: .7, resonance: .6 });
  assert.deepEqual(chooseValenceVoice({ ...h, lastIntake: 0, lastPoison: 0 } as V), { openness: .9, resonance: .1 });
  const goodSound = { visibleSourceId: null, shape: { openness: .2, resonance: .3 }, loudness: .4, relativePosition: { x: 5, y: 0 } };
  const badSound = { visibleSourceId: null, shape: { openness: .7, resonance: .6 }, loudness: .9, relativePosition: { x: -5, y: 0 } };
  assert.equal(selectSafeFood(h, [goodSound, badSound], () => 0.9), goodSound, "a sound tied to bad food is never followed, even when louder");
  assert.equal(selectSafeFood(h, [badSound], () => 0.1), null);
});
test("eating near a remembered sound source credits its category by the meal's outcome, and bad-food voices drop remembered food places", () => {
  const h = createHuman("A", {}, { hunger: .5 }) as V;
  h.heardSounds = [{ id: 1, shape: { openness: .2, resonance: .3 }, samples: 5 }];
  const low = { visibleSourceId: null, shape: { openness: .2, resonance: .3 }, loudness: .5, relativePosition: { x: 5, y: 0 } };
  const heard = decideValence(h, { tick: 0, selfPosition: { x: 10, y: 14 }, animals: [], resources: [], sounds: [low] }, () => 0.5).human as V;
  assert.equal(heard.recentSounds!.length, 1);
  const poisonedThere = { ...heard, lastIntake: .04, lastPoison: .04, places: { f: { kind: "food" as const, position: { x: 15.5, y: 14 }, strength: 1, seen: 10 } } } as V;
  const learned = decideValence(poisonedThere, { tick: 20, selfPosition: { x: 15, y: 14 }, animals: [], resources: [], sounds: [] }, () => 0.5).human as V;
  assert.ok(learned.valenceReferents!.bad[1].mean > 0 && learned.valenceReferents!.good[1].mean < 0, "a poisoned meal at the source ties the category to bad food");
  assert.equal(learned.places.f.strength, 0, "the poisoned place is dropped from the eater's memory");
  const wellThere = { ...heard, lastIntake: .04, lastPoison: 0 } as V;
  const learnedGood = decideValence(wellThere, { tick: 20, selfPosition: { x: 15, y: 14 }, animals: [], resources: [], sounds: [] }, () => 0.5).human as V;
  assert.ok(learnedGood.valenceReferents!.good[1].mean > 0);
  const warned = { ...h, valenceReferents: { good: {}, bad: { 1: { mean: .8, variance: .1, samples: 3 } } }, places: { f: { kind: "food" as const, position: { x: 16, y: 14 }, strength: 1, seen: 0 }, g: { kind: "food" as const, position: { x: 30, y: 5 }, strength: 1, seen: 0 } } } as V;
  const afterWarning = decideValence(warned, { tick: 30, selfPosition: { x: 10, y: 14 }, animals: [], resources: [], sounds: [low] }, () => 0.5).human as V;
  assert.equal(afterWarning.places.f.strength, 0, "a bad-food voice from near a remembered food place drops it");
  assert.equal(afterWarning.places.g.strength, 1, "far places are untouched");
  assert.equal(HUMAN_MODELS["valence-0.12.0-experimental.1"].apply, applyWithIntake);
});
test("valence-v1 makes every second spawned patch toxic, uses fresh seeds, and the poison measures compute and are oriented", () => {
  assert.equal((valence.world as unknown as { foodSpawn: { toxicEvery: number } }).foodSpawn.toxicEvery, 2);
  assert.equal(valence.resources.filter(r => (r as { toxic?: boolean }).toxic).length, 1);
  assert.deepEqual(valence.checks.map(c => c.id), ["convergence-gain", "arbitrariness", "convergence-bad", "valence-distinctness", "poison-benefit", "poison-shape", "forage-benefit"]);
  const all = [valence.pilotSeeds, seedsFor("development", valence, "1"), seedsFor("validation", valence, "1")].flat();
  assert.ok(new Set(all).size === all.length && all.every(s => s >= 70000));
  const state = createSimulation(referentialConfig(valence.pilotSeeds[0], "valence-0.12.0-experimental.1", true, valence));
  assert.ok(state.world.resources.some(r => r.toxic));
  const run = runExperiment({ ...referentialConfig(valence.pilotSeeds[0], "valence-0.12.0-experimental.1", true, valence), horizon: 60 });
  assert.equal(run.frames.length, 61);
  const r = runCondition("human-0.2.0", valence.pilotSeeds[1], "sound", { ...valence, horizon: 600 } as typeof valence);
  assert.ok(Number.isFinite(r.poisonIntake) && r.poisonIntake >= 0 && Number.isFinite(r.badVoiceDispersion));
  const seed: SeedResult = { seed: 1, model: "m", sound: { ...r, latePoisonIntake: 0.2, foodVoiceCentroid: { openness: .2, resonance: .3 }, badVoiceCentroid: { openness: .7, resonance: .6 }, badVoiceDispersion: 0.1 }, muted: { ...r, latePoisonIntake: 1.0, badVoiceCentroid: { openness: .5, resonance: .5 }, badVoiceDispersion: 0.3 }, misdirected: r, scrambled: { ...r, latePoisonIntake: 0.6 } };
  assert.ok(Math.abs(checkValue("poison-benefit", seed, valence) - 0.8) < 1e-9 && Math.abs(checkValue("poison-shape", seed, valence) - 0.4) < 1e-9);
  assert.ok(Math.abs(checkValue("convergence-bad", seed, valence) - 0.2) < 1e-9 && checkValue("valence-distinctness", seed, valence) > 0.5);
  const v5run = runCondition("human-0.2.0", 70101, "sound", { ...v5, horizon: 300 } as typeof v5);
  assert.equal(v5run.poisonIntake, 0, "worlds without toxic patches record no poison");
});
