import test from "node:test";
import assert from "node:assert/strict";
import { createHuman } from "../../packages/human/src/index.ts";
import { applyWithIntake } from "../../packages/human/src/forager-listener.ts";
import { decideValenceAversion, decideValenceDisgust, decideValenceDisgustPrivate, valenceOf, mealValenceOf, valenceCategory, AVERSION } from "../../packages/human/src/valence.ts";
import { protocol as valence } from "../../research/studies/valence-v1.ts";
import { protocol as valence2 } from "../../research/studies/valence-v2.ts";
import { protocol as valence3 } from "../../research/studies/valence-v3.ts";
import { protocol as valence4 } from "../../research/studies/valence-v4.ts";
import { seedsFor, referentialConfig, checkValue, type SeedResult } from "../../research/studies/referential-v1.ts";
import { HUMAN_MODELS, runExperiment } from "../../packages/simulation/src/index.ts";

type V = ReturnType<typeof createHuman> & { lastIntake?: number; lastPoison?: number; lastDisgust?: number; aversions?: { x: number; y: number; tick: number }[]; valenceHeard?: { good: Record<number, number>; bad: Record<number, number> }; valenceReferents?: { good: Record<number, { mean: number; variance: number; samples: number }>; bad: Record<number, { mean: number; variance: number; samples: number }> } };
const effect = (foodIntake: number, poison = 0) => ({ ambientCold: .3, foodIntake, exertion: 0, resting: false, collision: 0, ...(poison ? { poison } : {}) });
const patch = { id: "f", kind: "food" as const, strength: 1, relativePosition: { x: 1, y: 0 } };
const at = (tick: number, resources = [patch], sounds: { visibleSourceId: null; shape: { openness: number; resonance: number }; loudness: number; relativePosition: { x: number; y: number } }[] = []) => ({ tick, selfPosition: { x: 10, y: 14 }, animals: [], resources, sounds });
const hungry = () => createHuman("A", {}, { hunger: .6, fatigue: 0, cold: 0 });

test("food in sight at an aversive place is disgusting: a bad context without eating, with an urge to call; the aversion-only model stays silent about it", () => {
  const poisoned = applyWithIntake(hungry(), effect(.04, .04)) as V;
  const first = decideValenceDisgust(poisoned, at(10), () => 0.5).human as V;
  const calm = { ...first, lastPoison: 0, lastIntake: 0 } as V;
  const again = decideValenceDisgust(calm, at(30), () => 0.5);
  assert.equal((again.human as V).lastDisgust, 1, "the remembered bad place with food in sight is disgusting");
  assert.notEqual(again.action.kind, "forage");
  assert.ok(again.trace.scores.find(s => s.action === "vocalize")!.terms.callUrge! > 0, "disgust adds an urge to vocalize");
  assert.equal(valenceOf({ ...calm, lastDisgust: 1 } as V), "bad"); assert.equal(mealValenceOf({ ...calm, lastDisgust: 1 } as V), null, "disgust is a voice context, not a meal outcome");
  const away = decideValenceDisgust(calm, at(30, []), () => 0.5);
  assert.equal((away.human as V).lastDisgust, 0, "nothing in sight: no disgust");
  assert.equal(away.trace.scores.find(s => s.action === "vocalize")!.terms.callUrge, undefined);
  const plain = { ...calm } as V; delete plain.lastDisgust;
  const aversionOnly = decideValenceAversion(plain, at(30), () => 0.5);
  assert.equal((aversionOnly.human as V).lastDisgust, undefined, "experimental.2 never sets disgust");
  assert.equal(aversionOnly.trace.scores.find(s => s.action === "vocalize")!.terms.callUrge, undefined);
  const expired = decideValenceDisgust(calm, at(11 + AVERSION.ticks), () => 0.5);
  assert.equal((expired.human as V).lastDisgust, 0, "an expired aversion no longer disgusts");
});
test("comprehension mirrors production: a heard sound in the individual's own bad-voice category marks its source aversive; the deaf control does not", () => {
  const h = hungry() as V;
  h.heardSounds = [{ id: 1, shape: { openness: .2, resonance: .3 }, samples: 5 }, { id: 2, shape: { openness: .7, resonance: .6 }, samples: 5 }];
  h.valenceHeard = { good: { 1: 6 }, bad: { 2: 5 } };
  assert.equal(valenceCategory(h, "good"), 1); assert.equal(valenceCategory(h, "bad"), 2);
  const badSound = { visibleSourceId: null, shape: { openness: .7, resonance: .6 }, loudness: .8, relativePosition: { x: 2, y: 0 } };
  const goodSound = { visibleSourceId: null, shape: { openness: .2, resonance: .3 }, loudness: .8, relativePosition: { x: 2, y: 0 } };
  const heardBad = decideValenceDisgust(h, at(5, [patch], [badSound]), () => 0.5);
  assert.notEqual(heardBad.action.kind, "forage", "the patch next to the source of my own bad voice is not taken");
  assert.deepEqual((heardBad.human as V).aversions!.map(a => [a.x, a.y]), [[12, 14]]);
  const heardGood = decideValenceDisgust(h, at(5, [patch], [goodSound]), () => 0.5);
  assert.equal(heardGood.action.kind, "forage", "my good voice is not a warning");
  assert.equal((heardGood.human as V).aversions, undefined);
  const deaf = decideValenceDisgustPrivate(h, at(5, [patch], [badSound]), () => 0.5);
  assert.equal(deaf.action.kind, "forage", "the deaf control ignores heard bad voices");
  const noEstimate = decideValenceAversion(h, at(5, [patch], [badSound]), () => 0.5);
  assert.equal(noEstimate.action.kind, "forage", "experimental.2 needs a learned estimate above the warning level, which this individual lacks");
});
test("valence-v4 is registered with unit poison gates on fresh seeds, and the unit measures are plain differences", () => {
  assert.equal(HUMAN_MODELS["valence-disgust-0.12.0-experimental.3"].apply, applyWithIntake);
  assert.equal(HUMAN_MODELS["valence-disgust-private-0.12.0-experimental.3"].role, "control");
  assert.deepEqual(valence4.world, valence2.world);
  assert.deepEqual(valence4.checks.map(c => c.id), ["convergence-gain", "arbitrariness", "convergence-bad", "valence-distinctness", "poison-benefit-units", "poison-shape-units", "forage-benefit"]);
  const used = [valence, valence2, valence3].flatMap(p => [p.pilotSeeds, seedsFor("development", p, "1"), seedsFor("validation", p, "1")].flat());
  const v4 = [...seedsFor("development", valence4, "1"), ...seedsFor("validation", valence4, "1")];
  assert.equal(new Set([...used, ...v4]).size, used.length + v4.length);
  const run = (late: number) => ({ latePoisonIntake: late }) as unknown as SeedResult["sound"];
  const r = { seed: 1, model: "m", sound: run(0.4), muted: run(1.0), misdirected: run(1.0), scrambled: run(0.9) } as SeedResult;
  assert.ok(Math.abs(checkValue("poison-benefit-units", r, valence4) - 0.6) < 1e-9);
  assert.ok(Math.abs(checkValue("poison-shape-units", r, valence4) - 0.5) < 1e-9);
  const short = runExperiment({ ...referentialConfig(v4[0], "valence-disgust-0.12.0-experimental.3", true, valence4), horizon: 150 });
  assert.equal(short.frames.length, 151);
});
